substitutions:
  device_name: "workshop_distance"

esphome:
  name: $device_name
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:

logger:
  level: DEBUG  # Set to INFO for production

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sensor:
  - platform: dts6012m_uart
    name: "${device_name} Distance"
    id: distance_main
    update_interval: 30s
    accuracy_decimals: 3
    unit_of_measurement: "m"
    icon: "mdi:arrow-expand-vertical"
    filters:
      - delta: 0.01
      - throttle: 2s
    
    # Home Assistant automation triggers
    on_value:
      - if:
          condition:
            lambda: 'return x < 0.5;'
          then:
            - homeassistant.service:
                service: notify.mobile_app_phone
                data:
                  message: "Object detected very close to sensor!"
                  title: "Distance Alert"
    
    on_value_range:
      - above: 0.5
        below: 1.0
        then:
          - light.turn_on:
              id: warning_light
              brightness: 50%

binary_sensor:
  - platform: template
    name: "${device_name} Object Detected"
    id: object_detected
    lambda: |-
      if (id(distance_main).state < 2.0 && !isnan(id(distance_main).state)) {
        return true;
      } else {
        return false;
      }

light:
  - platform: binary
    name: "${device_name} Warning Light"
    id: warning_light
    output: warning_light_output

output:
  - platform: gpio
    pin: GPIO2
    id: warning_light_output